openapi: 3.0.0

info:
  title: Interactive Comments API 
  description: An API to manage data related to the interactive comments application
  version: 1.0.0

paths:

  /api/v1/users/{id}:

    get:
      summary: Get a single user by ID
      description: Get a single user by ID
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  email:
                    type: string
                  first_name:
                    type: string
                  last_name:
                    type: string

  /api/v1/users:

    get:
      summary: Get multiple users by ID
      description: Get multiple users by ID
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                    email:
                      type: string
                    first_name:
                      type: string
                    last_name:
                      type: string


