version: "3.8"

networks:
    network:
  
volumes:
    postgres:
    node_modules:

services:

    interactive-comments-app-react:
        stdin_open: true
        container_name: interactive-comments-app-react
        command: "sh entrypoint.sh"
        build:
            context: .
            dockerfile: ./frontend/docker/node/Dockerfile
        ports:
            - "8000:8000"
        volumes:
            # Store the node modules folder in a volume for performance
            - node_modules:/app/node_modules
            - "./frontend/:/app"
        networks:
            - network

    interactive-comments-app-nginx:
        image: nginx:stable-alpine
        container_name: interactive-comments-app-nginx
        ports:
            - "8080:80"
        volumes:
            - ./backend/src/public:/var/www/app/public
            - ./backend/docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - interactive-comments-app-php
            - interactive-comments-app-postgres
        networks:
            - network

    interactive-comments-app-postgres:
        image: postgres:14.3-alpine
        container_name: interactive-comments-app-postgres
        restart: always
        tty: true
        ports:
            - 5432:5432
        environment:
            POSTGRES_PASSWORD: secret
            POSTGRES_DB: interactive_comments
        volumes:
            - postgres:/var/lib/postgresql/data
        networks:
            - network
        cap_add:
            - SYS_NICE  # CAP_SYS_NICE

    interactive-comments-app-php:
        build:
            context: .
            dockerfile: ./backend/docker/php/Dockerfile
        image: interactive-comments-app-php
        container_name: interactive-comments-app-php
        tty: true
        working_dir: /var/www/app
        depends_on:
            - interactive-comments-app-postgres
        volumes:
            - ./backend/src:/var/www/app
        expose:
            - 9000
        networks:
            - network