version: "3.8"

networks:
    network:
  
volumes:
    mysql:
    node_modules:

services:

    interactive-comments-app-react:
        stdin_open: true
        container_name: interactive-comments-app-react
        command: "sh entrypoint.sh"
        build:
            context: .
            dockerfile: ./frontend/docker/node/Dockerfile
        ports:
            - "8000:8000"
        volumes:
            # Store the node modules folder in a volume for performance
            - node_modules:/app/node_modules
            - "./frontend/:/app"
        networks:
            - network

    interactive-comments-app-nginx:
        image: nginx:stable-alpine
        container_name: interactive-comments-app-nginx
        ports:
            - "8080:80"
        volumes:
            - ./backend/:/var/www/app
            - ./backend/docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - interactive-comments-app-php
            - interactive-comments-app-mysql
        networks:
            - network

    interactive-comments-app-mysql:
        image: mysql:8.0
        container_name: interactive-comments-app-mysql
        restart: unless-stopped
        tty: true
        ports:
            - 3306:3306
        environment:
            MYSQL_DATABASE: interactive-comments-appdb
            MYSQL_ROOT_PASSWORD: secret
        command: "--log-bin-trust-function-creators=1"
        volumes:
            - mysql:/var/lib/mysql
        networks:
            - network
        cap_add:
            - SYS_NICE  # CAP_SYS_NICE

    interactive-comments-app-php:
        build:
            context: .
            dockerfile: ./backend/docker/php/Dockerfile
        image: interactive-comments-app-php
        container_name: interactive-comments-app-php
        tty: true
        working_dir: /var/www/app
        volumes:
            - ./backend/:/var/www/app
        #command: /bin/sh -C "./entrypoint.dev.sh"
        depends_on:
            - interactive-comments-app-mysql
        expose:
            - 9000
        networks:
            - network