CREATE TABLE IF NOT EXISTS "comments" (
   id           UUID NOT NULL,
   author_id    UUID NOT NULL REFERENCES users (id) ON DELETE CASCADE,
   content      TEXT NOT NULL,
   created_at   TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
   PRIMARY KEY(id)
);